import{store}from'./firebase.js';import{defaultCards,dates}from'./data.js';import{newSalt,deriveKey,encrypt,decrypt}from'./crypto.js';
const $=s=>document.querySelector(s), app=$('#app'), sheetRoot=$('#sheet-root');
let cards=[],vaultCards=[],activeView='itinerary',activeDate='10/21',vaultKey=null,vaultMeta=null,unsubCards=null,unsubVault=null;
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2500)}
function closeSheet(){sheetRoot.innerHTML=''}function openSheet(html){sheetRoot.innerHTML=`<div class="sheet-backdrop"><section class="sheet">${html}</section></div>`;sheetRoot.querySelector('.sheet-backdrop').addEventListener('click',e=>{if(e.target===e.currentTarget)closeSheet()})}
function cardHtml(card,{vault=false}={}){const check=card.kind==='checklist';return `<article class="card ${card.checked?'done':''}"><button class="card-menu" data-action="menu" data-id="${esc(card.id)}" data-vault="${vault}">⋯</button>${check?`<label class="check"><input type="checkbox" data-action="toggle" data-id="${esc(card.id)}" ${card.checked?'checked':''}><div><div class="meta">${esc(card.category||'待辦')}</div><h3>${esc(card.title)}</h3><p>${esc(card.note)}</p></div></label>`:`<div class="meta">${esc(card.category||'行程')}${card.time?` · ${esc(card.time)}`:''}</div><h3>${esc(card.title)}</h3><p>${esc(card.note)}</p>`}</article>`}
function render(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===activeView));if(activeView==='itinerary')renderItinerary();else renderGuide(activeView)}
function renderItinerary(){const list=cards.filter(c=>c.section==='itinerary'&&(c.date||'10/21')===activeDate);const completed=cards.filter(c=>c.kind==='checklist'&&c.checked).length;const total=cards.filter(c=>c.kind==='checklist').length;app.innerHTML=`<section class="hero"><span class="chip">ORLANDO · OCT 21—31, 2026</span><h1>Your little<br>world of wonder.</h1><p>行程、提醒與私密旅行資料，都在這裡。</p></section><div class="quick-stats"><div class="stat"><strong>11</strong><small>旅行天數</small></div><div class="stat"><strong>${completed}/${total||0}</strong><small>待辦完成</small></div><div class="stat"><strong>3</strong><small>目的地</small></div></div><div class="date-row">${dates.map((d,i)=>`<button data-action="date" data-date="${d}" class="${d===activeDate?'active':''}">${d}<br><small>DAY ${i}</small></button>`).join('')}</div><div class="section-title"><b>${activeDate==='10/21'?'出發前待辦':`${activeDate} 的安排`}</b><button class="add-button" data-action="add-card">＋ 新增</button></div>${list.length?list.map(cardHtml).join(''):'<div class="empty">這一天還沒有安排。<br>按「新增」開始規劃吧！</div>'}`}
function renderGuide(section){const title=section==='cruise'?'Disney Wish':'EPCOT';const subtitle=section==='cruise'?'海上旅程的餐飲、娛樂與靠港提醒':'未來、自然與世界慶典的探索清單';const list=cards.filter(c=>c.section===section);const cats=[...new Set(list.map(c=>c.category))];const selected=app.dataset.category||cats[0];const visible=list.filter(c=>c.category===selected);const heroClass=section==='cruise'?'hero-cruise':'hero-epcot';const label=section==='cruise'?'PORT CANAVERAL · 2026':'WALT DISNEY WORLD · FLORIDA';app.innerHTML=`<section class="hero ${heroClass}"><span class="chip">${label}</span><h1>${title}</h1><p>${subtitle}</p></section><div class="filter-row">${cats.map(c=>`<button data-action="category" data-category="${esc(c)}" class="${c===selected?'active':''}">${esc(c)}</button>`).join('')}</div><div class="section-title"><b>${esc(selected||'旅程指南')}</b><button class="add-button" data-action="add-card">＋ 新增</button></div>${visible.length?visible.map(cardHtml).join(''):'<div class="empty">這個分類目前沒有卡片。</div>'}`}
async function saveCard(card){cards=cards.some(c=>c.id===card.id)?cards.map(c=>c.id===card.id?card:c):[...cards,card];render();try{await store.put('cards',card.id,{...card,updatedAt:new Date()})}catch(_){toast('已暫存在此裝置，待連線後同步')}}
async function deleteCard(id){cards=cards.filter(c=>c.id!==id);render();try{await store.remove('cards',id)}catch(_){toast('刪除將在重新連線後同步')}}
function openCardForm(card={section:activeView,date:activeView==='itinerary'?activeDate:'',kind:activeView==='itinerary'?'itinerary':'guide'},vault=false){openSheet(`<h2>${card.id?'編輯卡片':'新增卡片'}</h2><form id="card-form"><label>標題<input name="title" required value="${esc(card.title)}" placeholder="例如：確認登船時間"></label><label>分類<input name="category" value="${esc(card.category)}" placeholder="例如：住宿、餐飲、待辦"></label><label>時間／日期<input name="time" value="${esc(card.time)}" placeholder="例如：09:00"></label><label>內容<textarea name="note" placeholder="備註、地址或提醒">${esc(card.note)}</textarea></label><div class="sheet-actions"><button type="button" class="secondary" data-action="close-sheet">取消</button><button class="primary">儲存</button></div></form>`);$('#card-form').onsubmit=async e=>{e.preventDefault();const d=new FormData(e.target);const value={...card,id:card.id||crypto.randomUUID(),title:d.get('title').trim(),category:d.get('category').trim()||'未分類',time:d.get('time').trim(),note:d.get('note').trim(),updatedAt:new Date().toISOString()};if(vault){await saveVault(value)}else await saveCard(value);closeSheet();toast('已儲存')}}
function openMenu(id,isVault){const item=(isVault?vaultCards:cards).find(c=>c.id===id);if(!item)return;openSheet(`<h2>${esc(item.title)}</h2><div class="menu-list"><button data-action="edit" data-id="${esc(id)}" data-vault="${isVault}">✏️ 編輯</button>${isVault?'':`<button data-action="move-vault" data-id="${esc(id)}">🔒 移到保險箱</button>`}<button data-action="duplicate" data-id="${esc(id)}" data-vault="${isVault}">▣ 複製</button><button class="danger" data-action="delete" data-id="${esc(id)}" data-vault="${isVault}">🗑 刪除</button></div>`)}
async function moveToVault(id){if(!vaultKey)return toast('請先解鎖保險箱');const card=cards.find(c=>c.id===id);if(!card)return;await saveVault({...card,id:crypto.randomUUID(),movedAt:new Date().toISOString()});await deleteCard(id);closeSheet();toast('已移到保險箱')}
async function saveVault(card){if(!vaultKey)throw new Error('Vault locked');vaultCards=vaultCards.some(c=>c.id===card.id)?vaultCards.map(c=>c.id===card.id?card:c):[...vaultCards,card];renderVault();const encrypted=await encrypt(card,vaultKey);await store.put('vault',card.id,{...encrypted,updatedAt:new Date()})}
async function deleteVault(id){vaultCards=vaultCards.filter(c=>c.id!==id);renderVault();await store.remove('vault',id)}
function renderVault(search=''){const term=search.trim().toLowerCase();const list=vaultCards.filter(c=>`${c.title} ${c.note} ${c.category}`.toLowerCase().includes(term));app.innerHTML=`<section class="hero hero-vault"><span class="chip">AES-256-GCM · PRIVATE</span><h1>Only yours.</h1><p>PIN 只在這台裝置用於解鎖；雲端不保存任何明文內容。</p></section><input class="search" id="vault-search" value="${esc(search)}" placeholder="⌕ 搜尋保險箱內容"><div class="section-title"><b>${list.length} 筆安全資料</b><button class="add-button" data-action="add-vault">＋ 新增</button></div>${list.length?list.map(c=>cardHtml(c,{vault:true})).join(''):'<div class="empty">還沒有保險箱資料。</div>'}`;$('#vault-search').oninput=e=>renderVault(e.target.value)}
async function readVault(){if(unsubVault)unsubVault();unsubVault=store.watch('vault',async rows=>{if(rows===null)return;const decoded=[];for(const row of rows){if(row.id==='_check')continue;try{decoded.push(await decrypt(row,vaultKey))}catch(_){}}vaultCards=decoded;renderVault()})}
async function vaultEntry(){$('#drawer').classList.remove('open');if(!store.db)return toast('離線時無法驗證保險箱');vaultMeta=await store.one('settings','vault-meta');showPin(vaultMeta?'unlock':'create')}
function showPin(mode){let digits='',first='';const labels={create:['建立保險箱 PIN','請設定 4 位數 PIN'],unlock:['保險箱已鎖定','輸入 PIN 以解鎖'],change:['變更 PIN','先輸入目前的 PIN']};const paint=(message='')=>{app.innerHTML=`<section class="pin-screen"><div class="pin-box"><div class="pin-lock">🔒</div><h1>${labels[mode][0]}</h1><p class="${message?'pin-error':''}">${message||labels[mode][1]}</p><div class="pin-dots">${'●'.repeat(digits.length)}${'○'.repeat(4-digits.length)}</div><div class="pin-pad">${[1,2,3,4,5,6,7,8,9].map(n=>`<button data-pin="${n}">${n}</button>`).join('')}<button data-action="pin-cancel" class="erase">取消</button><button data-pin="0">0</button><button data-action="pin-erase" class="erase">⌫</button></div></div></section>`};const accept=async()=>{const pin=digits;digits='';try{if(mode==='create'){if(!first){first=pin;labels.create[1]='再輸入一次以確認';paint();return}if(pin!==first){first='';labels.create[1]='兩次 PIN 不相同，請重新設定';paint('兩次 PIN 不相同');return}vaultMeta={salt:newSalt(),version:1};vaultKey=await deriveKey(pin,vaultMeta.salt);await store.put('settings','vault-meta',vaultMeta);await store.put('vault','_check',await encrypt({type:'vault-check'},vaultKey));toast('保險箱已建立')}else if(mode==='unlock'){vaultKey=await deriveKey(pin,vaultMeta.salt);const check=await store.one('vault','_check');const marker=await decrypt(check,vaultKey);if(marker.type!=='vault-check')throw new Error('invalid')}else{const oldKey=await deriveKey(pin,vaultMeta.salt);const check=await store.one('vault','_check');await decrypt(check,oldKey);vaultKey=oldKey;return showNewPin()}await readVault()}catch(_){vaultKey=null;paint('PIN 不正確，請再試一次')}};app.onclick=e=>{const n=e.target.dataset.pin;if(n!==undefined){digits+=n;if(digits.length===4)accept();else paint()}if(e.target.dataset.action==='pin-erase'){digits=digits.slice(0,-1);paint()}if(e.target.dataset.action==='pin-cancel'){activeView='itinerary';render()}};paint()}
async function showNewPin(){const encrypted=await store.all('vault');const contents=[];for(const row of encrypted){if(row.id==='_check')continue;contents.push(await decrypt(row,vaultKey))}let digits='',first='';const paint=(message='')=>{app.innerHTML=`<section class="pin-screen"><div class="pin-box"><div class="pin-lock">🔐</div><h1>Set new PIN</h1><p class="${message?'pin-error':''}">${message||'Enter a new 4 digit PIN'}</p><div class="pin-dots">${'●'.repeat(digits.length)}${'○'.repeat(4-digits.length)}</div><div class="pin-pad">${[1,2,3,4,5,6,7,8,9].map(n=>`<button data-pin="${n}">${n}</button>`).join('')}<button data-action="pin-cancel" class="erase">Cancel</button><button data-pin="0">0</button><button data-action="pin-erase" class="erase">⌫</button></div></div></section>`};const accept=async()=>{const pin=digits;digits='';if(!first){first=pin;paint('Enter it again to confirm');return}if(pin!==first){first='';paint('PINs do not match');return}try{const meta={salt:newSalt(),version:1};const key=await deriveKey(pin,meta.salt);await store.put('settings','vault-meta',meta);await store.put('vault','_check',await encrypt({type:'vault-check'},key));await Promise.all(contents.map(c=>encrypt(c,key).then(payload=>store.put('vault',c.id,payload))));vaultMeta=meta;vaultKey=key;vaultCards=contents;toast('PIN changed and vault re-encrypted');await readVault()}catch(_){paint('Could not change PIN')}};app.onclick=e=>{const n=e.target.dataset.pin;if(n!==undefined){digits+=n;if(digits.length===4)accept();else paint()}if(e.target.dataset.action==='pin-erase'){digits=digits.slice(0,-1);paint()}if(e.target.dataset.action==='pin-cancel'){activeView='itinerary';render()}};paint()}
async function settings(){closeSheet();openSheet(`<h2>設定</h2><div class="setting-row"><span>雲端同步</span><b id="settings-sync">${store.db?'已連線':'離線'}</b></div><div class="setting-row"><span>保險箱 PIN</span><button class="secondary" data-action="change-pin">變更 PIN</button></div><div class="sheet-actions" style="margin-top:18px"><button class="secondary" data-action="close-sheet">完成</button></div>`)}
async function changePin(){closeSheet();vaultMeta=await store.one('settings','vault-meta');if(!vaultMeta)return showPin('create');showPin('change')}
async function share(){const clean=new URL(location.href);clean.hash='';try{if(navigator.share)await navigator.share({title:'Disney Travel Planner',url:clean.href});else{await navigator.clipboard.writeText(clean.href);toast('分享連結已複製（不含保險箱資料）')}}catch(_){}}
function handleClick(e){const b=e.target.closest('[data-action]');if(!b)return;const{action,id,vault,date,category}=b.dataset;if(action==='date'){activeDate=date;render()}if(action==='category'){app.dataset.category=category;renderGuide(activeView)}if(action==='add-card')openCardForm();if(action==='add-vault')openCardForm({kind:'vault',section:'vault'},true);if(action==='menu')openMenu(id,vault==='true');if(action==='close-sheet')closeSheet();if(action==='edit'){const c=(vault==='true'?vaultCards:cards).find(x=>x.id===id);closeSheet();openCardForm(c,vault==='true')}if(action==='move-vault')moveToVault(id);if(action==='duplicate'){const c=(vault==='true'?vaultCards:cards).find(x=>x.id===id);if(c){closeSheet();openCardForm({...c,id:null,title:`${c.title}（副本）`},vault==='true')}}if(action==='delete'){if(confirm('確定要刪除這張卡片？')){vault==='true'?deleteVault(id):deleteCard(id);closeSheet();toast('已刪除')}}if(action==='toggle'){const c=cards.find(x=>x.id===id);if(c)saveCard({...c,checked:e.target.checked})}}
async function boot(){app.addEventListener('click',handleClick);$('#menu-button').onclick=()=>$('#drawer').classList.add('open');document.querySelectorAll('.close-drawer').forEach(x=>x.onclick=()=>$('#drawer').classList.remove('open'));$('#drawer').onclick=e=>{if(e.target===$('#drawer'))$('#drawer').classList.remove('open')};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{activeView=b.dataset.view;$('#drawer').classList.remove('open');render()});$('#vault-entry').onclick=vaultEntry;$('#settings-entry').onclick=settings;$('#share-button').onclick=share;const online=await store.init(state=>$('#sync-state').textContent=state);if(online){unsubCards=store.watch('cards',async remote=>{if(remote===null)return;if(!remote.length){const seeded=await store.one('settings','seed-v2');if(!seeded){await Promise.all(defaultCards.map(c=>store.put('cards',c.id,{...c,updatedAt:new Date()})));await store.put('settings','seed-v2',{done:true})}}else{cards=remote;render()}})}else{cards=JSON.parse(localStorage.getItem('disney-v2-cards')||'null')||defaultCards;render()}render()}
window.addEventListener('online',()=>$('#sync-state').textContent='網路已恢復');window.addEventListener('offline',()=>$('#sync-state').textContent='離線快取');boot();
